import {StyleSheet} from 'react-native';
import {colors, shadows} from '../../themes';

export default StyleSheet.create({
  container: {},
  title: {
    fontFamily: 'Raleway',
    fontWeight: 'bold',
    letterSpacing: 1.2,
    fontSize: 30,
    color: colors.white,
    paddingHorizontal: 10,
    position: 'absolute',
    bottom: 20,
  },
  closeButton: {
    position: 'absolute',
    top: 50,
    right: 10,
    paddingTop: 4,
    borderRadius: 20,
    marginRight: 10,
    ...shadows.globalShadow,
    zIndex: 999,
  },
  gradient: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  infoContainer: {
    backgroundColor: colors.greyBackground,
    paddingVertical: 15,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  infoBlock: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '30%',
    borderWidth: 1,
    borderColor: colors.greyBorder,
    borderRadius: 10,
    padding: 10,
  },
  infoLabel: {
    width: '100%',
    textAlign: 'center',
    fontSize: 10,
    fontWeight: 'bold',
    backgroundColor: colors.blueGrey,
    borderRadius: 5,
    overflow: 'hidden',
    paddingVertical: 3,
    paddingHorizontal: 10,
    marginBottom: 5,
    color: colors.white,
  },
  infoCopy: {
    color: colors.blueGrey,
    marginTop: 5,
  },
  ingredientsButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  ingredientsContainer: {
    backgroundColor: colors.greyBorder,
  },
  ingredientsTitle: {
    fontFamily: 'Raleway',
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.blueGrey,
  },
  ingredientBlock: {
    flexDirection: 'row',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderColor: colors.lightGrey,
    paddingHorizontal: 10,
  },
  ingredientInfo: {
    marginLeft: 10,
  },
  ingredientImage: {
    backgroundColor: colors.white,
    borderRadius: 10,
  },
  ingredientName: {
    fontSize: 18,
    color: colors.blueGrey,
    marginBottom: 5,
  },
  ingredientAmount: {
    fontSize: 16,
    color: colors.darkGrey,
  },
  instructionsContainer: {
    paddingBottom: 100,
  },
  instructionsTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 20,
    fontFamily: 'Raleway',
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.blueGrey,
  },
  instructionBlock: {
    flexDirection: 'row',
    paddingVertical: 25,
    borderTopWidth: 1,
    borderColor: colors.greyBorder,
    paddingHorizontal: 10,
  },
  instructionStep: {
    fontFamily: 'Raleway',
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.blueGrey,
    marginBottom: 10,
  },
  instructionCopy: {
    fontSize: 16,
    lineHeight: 25,
    color: colors.darkGrey,
  },
});
